blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^c(?P<category_id>[0-9]+)/$',views.c_detail,name='c_detail'),
    url(r'^b(?P<blog_id>[0-9]+)/$',views.b_detail,name='b_detail'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.category

class Blog(models.Model):
    data = models.CharField(max_length=5000)
    title = models.CharField(max_length=150)
    pub_date = models.DateTimeField('date published')
    publisher = models.CharField(max_length=30)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from .models import Category, Blog

def index(request):
    category_list = Category.objects.order_by('id')[:5]
    context = {'category_list': category_list}
    return render(request, 'blog/index.html', context)

def b_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/b_detail.html', {'blog': blog,'error_message': "You didn't select a choice.",})

def c_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'blog/c_detail.html', {'category': category,'error_message': "You didn't select a choice.",})

blog/templates/blog/b_detail.html
<h1>{{ blog.title }}</h1>
<p><pre>{{ blog.data }}</pre></p>
Written by: {{ blog.publisher}}<br>
Date: {{blog.pub_date}}<br><br>

blog/templates/blog/c_detail.html
<h1>{{ category.category }}</h1>
<ul>
{% for blog in category.blog_set.all %}
    <li><a href="{% url 'b_detail' blog.id %}">{{ blog.title }}</a></li>
{% endfor %}
</ul>

blog/templates/blog/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}" />

{% if category_list %}
<h1>Category List</h1>
    <ul>
    {% for category in category_list %}
        <li><a href="{% url 'c_detail' category.id %}">{{ category.category }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No category are available.</p>
{% endif %}